swagger: "2.0"
info:
  title: Epol Test
  description: 'This is a sample server '
  contact:
    email: kny.5298@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
- name: users
  description: Operations about user
- name: auth
  description: Operations for Authentication
paths:
  /users:
    post:
      tags:
      - users
      summary: Create user
      parameters:
      - in: "body"
        name: "body"
        schema:
          $ref: '#/definitions/CreateUser'
        required: true
      responses:
        200:
          description: successful operation'
          schema:
            $ref: '#/definitions/User'
        401:
          $ref: '#/responses/UnauthorizedError'
        405:
          description: "Invalid input"
      security:
      - api_key: []
    get:
      tags:
      - users
      summary: Get users 
      responses:
        200:
          description: successful operation'
          schema:
            items:
              $ref: '#/definitions/User'
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
      - api_key: []
  /users/{userId}:
    get:
      tags:
      - users
      summary: Get user by userId
      parameters:
      - name: userId
        in: path
        description: 'The userId that needs to be fetched.'
        required: true
        type: string
        pattern: "^[a-f\d]{24}$"
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        400:
          description: Invalid userId supplied
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          description: User not found
      security:
      - api_key: []
    put:
      tags:
      - users
      summary: Updated user
      parameters:
      - name: userId
        in: path
        description: 'The userId that needs to be updated.'
        required: true
        type: string
        pattern: "^[a-f\d]{24}$"
      - in: "body"
        name: "body"
        schema:
          $ref: '#/definitions/CreateUser'
        required: true
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        400:
          description: Invalid user supplied
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          description: User not found
      security:
      - api_key: []
    delete:
      tags:
      - users
      summary: Delete user
      parameters:
      - name: userId
        in: path
        description: 'The userId that needs to be deleted'
        required: true
        type: string
        pattern: "^[a-f\d]{24}$"
      responses:
        200:
          description: successful operation
          schema:
            items:
              $ref: '#/definitions/User'
        400:
          description: Invalid username supplied
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          description: User not found
      security:
      - api_key: []
  /login:
    post:
      tags:
      - auth
      summary: Login user
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
        required: true
      responses:
        200:
          description: successful operation'
          schema:
            properties:
              token:
                type: string
        405:
          description: "Invalid input"
responses:
  UnauthorizedError:
    description: API key is missing or invalid
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
    CreateUser:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        organizationName:
          type: string
    User:
      type: object
      properties:
        _id:
          type: object
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        organizationName:
          type: string